### ISSUE TITLE
Default Base for "exports" Paths

### ISSUE THREAD

**Issue by SMotaal** [jkrems/proposal-pkg-exports#15]
A subtle but not insignificant aspect of the "export" path values is that in current examples they start with "./" so some questions feel needed to be raised:

1. Is it expected that a path would not start with "./"?
2. If it does:
   a. Does that include starting with "../"?
   b. Then, how does that translate for portability? (ie mapping "../" outside node_modules)
3. If not:
   a. Do we want to limit maps to package scope? (ie mapping a crafty "../" not allowed)
   b. Then, do we want to support bare references? (ie mapping "other-package/{key})

Those questions are important to address long term, but for now and for the sake of brevity, do we want to consider the preceding "./" to be implied?

**Comment by guybedford** [comment]
These are very good questions!

Personally I am on the side of restricting the variations to what is sensible, and throwing in cases like `../` or even where there are internal dot segments in paths.

I think we should be explicit though with the leading `./` so that someone who has never seen the spec before can get a clear understanding of where it is pointing.

**Comment by hybrist** [comment]
I think right now the spirit of the proposal is "you may only map to things inside of the package boundary". This becomes a bit tricky when `package.json` files in subdirectories come into play but what matters to me is more the "package-as-published" and less the "package-on-disk". And there it should be fairly clear (if it is in the thing you'd upload to npm, then it should be mappable).

From a spec perspective: Right now I would say we should restrict to "starts with ./" and call anything else "reserved". E.g. I could see some fun uses of absolute URLs in the future but that's really speculative.

**EDIT:** Starts with "./" and may not contain "/../" or something like that..?

**Comment by SMotaal** [comment]
So we are talking something like a condition `new URL(exportPath, packageScope).href.startsWith(packageScope) === true` and where `packageScope.endsWith('/') === true`.

**Edit**: and for now ``if (!exportPath.startsWith('./')) throw URIError(`Unsupported: Export paths like "${exportPath}" are not currently supported since it does not begin with "./".`)``

**Comment by hybrist** [comment]
We now validate that relative URLs may not leave the package boundary (and we don't support absolute URLs yet).
