### ISSUE TITLE
Alternative to `/` scoping

### ISSUE THREAD

**Issue by guybedford** [jkrems/proposal-pkg-exports#18]
An alternative here could be to use `./` over `/`:

```json
{
  "exports": {
    "./path": "./path"
  }
}
```

This might avoid confusion with `/` meaning the root in the map.

**Comment by hybrist** [comment]
+1, also nice from a symmetry perspective (even though it's slightly more verbose).

**Comment by SMotaal** [comment]
I was thinking the exact same thing because “./“ without a path is “/“ whereas “.” could be the root entry “.” should that ever be intended or even be conceivable.

This was in the context of avoiding “” if I am not mistaken, right?

**Comment by hybrist** [comment]
This happened!
