### ISSUE TITLE
Review - spec work

### ISSUE THREAD

**Issue by guybedford** [jkrems/proposal-pkg-exports#21]
I did some spec work here at https://github.com/guybedford/ecmascript-modules/compare/irp...guybedford:irp-exports which is a PR against the import file specifier resolution proposal spec at https://github.com/nodejs/ecmascript-modules/pull/19.

Feedback welcome.

**Comment by guybedford** [comment]
I managed to finish the initial implementation work at https://github.com/guybedford/node/tree/irp-implementation

**Comment by hybrist** [comment]
I think we have a working spec in the ESM and CJS docs now. Closing but please reopen if this is still something that needs work!
