### ISSUE TITLE
Basic implementation for experimentation

### ISSUE THREAD

**Issue by coreyfarrell** [jkrems/proposal-pkg-exports#33]
I've created a patch for [babel-plugin-bare-import-rewrite](https://github.com/cfware/babel-plugin-bare-import-rewrite/tree/proposal-pkg-exports#experimentalpkgexports) which has an option to enable experimentation with proposal-pkg-exports.  Although the original goal of that plugin is to support live transformation of bare imports through a web server like [express-transform-bare-module-specifiers](https://www.npmjs.com/package/express-transform-bare-module-specifiers), it is also able to operate with `@babel/register` in node.js processes.  https://github.com/cfware/babel-plugin-bare-import-rewrite/blob/proposal-pkg-exports/fixtures/pkg-exports-bin.js demonstrates this.

I haven't released this feature to npm yet, is it interesting to anyone?  One potential issue it operates using the less strict `--es-module-specifier-resolution=node` mode.  Obviously this is only useful for testing pkg-exports without node.js native ESM since @babel/register does not work with native ESM.

**Comment by hybrist** [comment]
That looks like really need, thanks for the ping!

**Comment by hybrist** [comment]
I'm going to close this issue to make it a bit clearer what threads need conclusion before we can ship `exports`. We're getting close to finalizing the implementation!

**Comment by coreyfarrell** [comment]
Sounds reasonable, I'm going to leave my experimental branch in place for now but I suspect it's diverged from the current spec.  Will likely wait for `resolve` to have support for `exports` lookup before I take any further action.

**Comment by ljharb** [comment]
@coreyfarrell as soon as i know what node version it will land in, i'll add it :-)
