### ISSUE TITLE
Blocking paths/files inside an exported path

### ISSUE THREAD

**Issue by coreyfarrell** [jkrems/proposal-pkg-exports#37]
```js
{
  "name": "foo-bar",
  "exports": {
    "./timezones/": "./data/timezones/",
    "./timezones/private.js": false,
    "./timezones/private/": false
  }
}
```

Has this type of functionality been discussed/considered?  The idea is this would allow import of `foo-bar/timezones/edt.js` but forbid import of `foo-bar/timezones/private/edt.js` or `foo-bar/timezones/private.js`.  Even if not documented I wouldn't be surprised to see people try to do this or using `"./timezones/private/": "./suppress-direct-import-of-privates-with-invalid-path/"`.

**Comment by SMotaal** [comment]
I think it was considered but not in the concrete sense that those are **private** modules.

That said, and while I completely dig the simplicity and clarity, I feel more inclined to think of this out of immediate scope (ie worth discussing in due time if so) — Sorry for being blunt, but that is my personal take, and others might prove me completely off here :)

**Comment by ljharb** [comment]
By specifying an exports map, every file is already implicitly false - so you can achieve what you want merely by not listing those entry points.

**Comment by demurgos** [comment]
Package-private modules are definitely something that would be nice to offer. Even if they are currently out of scope, I feel that they could belong to the package export config: it describes the public interface of the package.
A common situation where I wish it was supported is when I have re-exports in my lib package and my IDE's auto-import feature picks the internal module instead of the reexport.

I think that a even simpler design would be to use the config as a whitelist: only listed packages would be allowed (**edit**: I see that @ljharb posted the same idea while I was typing). Maybe a flag could be added to ask Node to check this policy at runtime to enforce that only whitelisted modules are importable?
**Edit**: I forgot the resolution already errors if there's no match.

**Comment by ljharb** [comment]
@demurgos it’s not an idea, it’s how the proposal already works

**Comment by coreyfarrell** [comment]
@ljharb the value `"./timezones/": "./data/timezones/"` causes everything within data/timezones/ to be exposed under `foo-bar/timezones/**`.  So `import something from 'foo-bar/timezones/private.js'` would be allowed by that exports key, the question here is about the ability to block specific paths within a folder that is exported.

**Comment by ljharb** [comment]
aha, my apologies. I think then that that should still work as is, because the value you pass on the RHS can’t be resolved.

**Comment by ljharb** [comment]
You could also put a package.json in that folder that had its own exports map, I’d think?

**Comment by hybrist** [comment]
I would assume that the behavior will align with the approach taken by import maps (once that's more stable). This means looking at the situation today:

```
{
  "name": "foo-bar",
  "exports": {
    "./timezones/": "./data/timezones/",
    "./timezones/private.js": null,
    "./timezones/private/": null
  }
}
```

But just in terms of project maintenance, mixing private files inbetween things that are publicly accessible seems like asking for trouble. So I'm not sure we should prioritize it at this point.

**Comment by guybedford** [comment]
@jkrems what does import maps do for `null` mappings?

**Comment by hybrist** [comment]
It's an alternate syntax for `[]` ("no mapping"): https://github.com/WICG/import-maps#denying-access-to-a-built-in-module

**Comment by guybedford** [comment]
Interesting, I guess we could support it similarly then, if/when this is demonstrated to be a stable feature.

**Comment by hybrist** [comment]
I think this will come up when we add support for arrays in general since then it falls out pretty natural. But for that I want to punt on what exactly the fallback semantics end up being for import maps (e.g. if multiple arbitrary URLs can be used for example).

**Comment by coreyfarrell** [comment]
@jkrems I agree that it's probably best to avoid structuring a project as I suggested in this ticket but it will happen.  My hope here is to eliminate the edge case where projects might decide to use potentially unspecified behavior to suppress parts of an exported directory.

**Comment by hybrist** [comment]
Empty arrays should work as a way to selectively disallow/un-export files inside of an exported directory. Adding support for the `null` sugar would at most be a minor cosmetic change.

**Comment by ljharb** [comment]
@jkrems it's a useful thing to consider, though - have we specified what happens with a non-array, non-string value?

**Comment by hybrist** [comment]
non-array, non-string values will be ignored in the current implementation. We're trying to define a syntax where bundlers and/or future versions of node could use them for advanced features like differential mappings based on the environment / feature support. So to allow package owners to publish backwards-compatible packages, we have to completely ignore those (reserved) values.
