### ISSUE TITLE
Finalize decision on `package.json` field name

### ISSUE THREAD

**Issue by hybrist** [jkrems/proposal-pkg-exports#5]
Known constraints:

1. May not collide with existing ecosystem usage.
1. Should be a valid JavaScript identifier, e.g. camelcase or single word.

**Comment by GeoffreyBooth** [comment]
Options we discussed while drafting the proposal:

- `exports`
- `nodejs.module`, avoids the awkwardness between singular and plural and is namespaced so as not to conflict with the commonly used top-level `module`
- `export`
- `entries`
- `moduleExports`

We wrote the proposal with `esm-exports` as a deliberately awful name to encourage replacement, but changed it at the last minute as we realized it wasn’t a valid identifier (that would’ve been `esmExports` but that felt too awful even as a placeholder).

**Comment by sokra** [comment]
* `externalImports`

Would align with the `"imports"` property in import maps. `external` because it only affects imports from outside of the package.

This leaves room for adding `internalImports` as import map for package internal specifiers.

**Comment by guybedford** [comment]
@sokra we previously considered `"imports"` or something like Parcel's `"aliases"` as the internal dual here. Definitely open to further discussion on that. `"exports"` already has consensus though for now, so it would be shame to go back to that bikeshed at this point, but we could if there are good reasons.

**Comment by hybrist** [comment]
To echo @guybedford I feel like we should close this issue. There doesn't seem to be much pushback to `exports` and it's what already is implemented. I would like to treat it as an exception if we'd have to change the field name(s) at this point.
