### ISSUE TITLE
Define exact character sets for mapping

### ISSUE THREAD

**Issue by hybrist** [jkrems/proposal-pkg-exports#6]
What may appear on the LHS (the specifier key)?
  - restricting on pkg name char set?
  - URL char set?
  - All characters go?

```js
{
  "exports": {
    "/🍕 & 🍔": "./pizza%20and%20burger.js"
  }
}
```

**Comment by guybedford** [comment]
It can useful to enable forward compatibility by not being too hard on validation.

Here's what I'd suggest:

1. Only match LHS "valid specifiers", where those are defined by character set checks on the subpath being imported - `import 'pkg/🍕 & 🍔'` throwing as opposed to the existing of pizza throwing :P
2. Similarly validate the RHS as the resolution is handled, and enforce that the RHS must start with `./` and not contain `..` or `.` segments, or encoded `/` or `\\`.

If that sounds sensible, I can aim to write something up along these lines. This is one of the main things to think about for the spec I think.

**Comment by hybrist** [comment]
That sounds sensible. To clarify on (1): I assume this is about *when* we are checking, not necessarily what character set is allowed? E.g. your exports map is accepted, no matter what the keys are. But when resolving imports, we fail early and potentially wouldn't even load the map if the specifier in the import contains characters we don't support?

**Comment by guybedford** [comment]
Exactly, we don't validate the object, we validate the resolutions we attempt.

We could even fail softly when the RHS is an object to support forwards compatibility with new features. This concept of forwards compatibility through soft failures has also applied to imports name maps validations - https://github.com/domenic/import-maps/issues/80.

**Comment by hybrist** [comment]
We now have semantics that are implemented, including restrictions on patterns and targets. So I feel like this is now defined?
